### ISSUE TITLE
Mac OS X Support

### ISSUE THREAD

**Issue by ikappas** [ilich/vscode-launcher#10]
I cant seem to run this in Mac OS X

**Comment by cloudbeer** [comment]
me too even i changed user setting launcher.terminal to /Applications/iTerm.app

**Comment by ilich** [comment]
Unfortunately I do not have Mac OS X to test the extension. I used VS Code source code to find out how to launch default Mac OS X terminal.

``` ts
import cp = require("child_process");

// ...

} else if (process.platform === "darwin") {
    executable = "iTerm.sh";
    parameters = "";
}

// ...

cp.exec(...)
```

Please send a pull request if you know a way to launch executable on Mac using Node.js child_process module.

**Comment by jonigl** [comment]
Same here! :(
