### ISSUE TITLE
Long Filename Not Working

### ISSUE THREAD

**Issue by SenseiJoe** [ilich/vscode-launcher#3]
Trying to launch firefox using long filename doesn't work.  Need to use short path for it to work.
    {
        "description": "Firefox-Works",
        "executable": "c:\progra~2\mozill~1\firefox.exe",
        "parameters": "localhost:740"
    },  
    {
        "description": "Firefox 2-Doesn't Work",
        "executable": "c:\Program Files (x86)\Mozilla Firefox\firefox.exe",
        "parameters": "localhost:740"
    },

**Comment by ilich** [comment]
I fixed the issue. Please update the extension. Thank you for the report!

**Comment by SenseiJoe** [comment]
Works great, thanks for the quick fix.
