### ISSUE TITLE
unable to start cmder on directory

### ISSUE THREAD

**Issue by dgpgdev** [ilich/vscode-launcher#5]
i can't launch cmder terminal on directory or file. 

"launcher.terminal": {
    "description": "Cmder (item)",
    "parameters": "/start %item_path%",
    "executable": "E:\cmder\Cmder.exe"
} (not work)

"launcher.terminal": {
    "description": "Cmder (workspace)",
    "parameters": "/start %workspace%",
    "executable": "E:\cmder\Cmder.exe"
} (not work)

"launcher.terminal": {
    "description": "Cmder (workspace)",
    "parameters": "/start",
    "executable": "E:\cmder\Cmder.exe",
"startIn":"%item_path%"
} (not work)

how can i solve this problem ?

**Comment by ilich** [comment]
An executable should be full executable path with an extension. Take a look to #2.
