### ISSUE TITLE
Add support for platform

### ISSUE THREAD

**Issue by Beatusvir** [ilich/vscode-launcher#6]
So we can have a set of commands depending on platform.

I use windows @ work, Archlinux @ home.
I don't think my Archlinux likes cmd.exe, and my settings are synced. :sob: 

I'll check the code maybe I can contribute a little.

**Comment by ilich** [comment]
I am using xterm on Linux. Take a look to https://github.com/ilich/vscode-launcher/blob/master/src/command.ts (line 96). Try Ctrl-Alt-T and Ctrl-Alt-Shift-T on your Linux machine. If it does not work then you can create custom menu entry in your user profile.

Anyway, if you have better solution for Archlinux send me a pull request, please.

**Comment by Beatusvir** [comment]
@ilich Oh I see, it's perfect then :+1:, Sorry tbh all the documentation referenced windows so I thought it was executing cmd.exe directly unless you changed the terminal command in settings and we could only use the same command for every platform.
