### ISSUE TITLE
when i start the laucher on vscode... not recognize npm commands 

### ISSUE THREAD

**Issue by leonardotessaroalves** [ilich/vscode-launcher#7]
the setting works:

"launcher.terminal": {
    "executable": "gnome-terminal"  
}

but, when i tryed to run for ex:  npm start ... ERR...

watch: https://www.youtube.com/watch?v=SXpYtcCjaP8

**Comment by ilich** [comment]
It was hard to find out what was wrong from the view. I think you might have a problem with setting up current directory where to start `npm start`. Try something similar to

``` json
{
        "description": "Bash (Workspace)",
        "executable": "C:\\Users\\User1\\AppData\\Local\\Programs\\Git\\git-bash.exe",
        "startIn": "%workspace%"
}
```

Please also take a look to issue #2. It might be helpful.

Let me know if it still does not work. Please provide the steps to recreate the issue.
