### ISSUE TITLE
How to use vsce package?

### ISSUE THREAD

**Issue by red-auto** [ilich/vscode-launcher#8]
I can not find your email... so open an issue.
1. download from https://github.com/ilich/vscode-launcher/archive/master.zip
2. edit the file vscode-launcher-master/src/command.ts
3. cd C:\Users\a\Desktop\vscode-launcher-master;
   vsce package
4. I get an error
   Error: Cannot find module 'C:\Users\a\Desktop\vscode-launcher-master\node_modules\vscod\bin\compile'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Function.Module.runMain (module.js:441:10)
   at startup (node.js:139:18)
   at node.js:968:3

Could you show how to use vsce package with vscode-launcher?

**Comment by ilich** [comment]
VSCE is the tool to publish the plugin to Marketplace. These are the steps to start development:
1. `git clone https://github.com/ilich/vscode-launcher`
2. `cd vscode-launche`
3. `npm install`. This command will install all required packages.

Now you can open source code in VS Code and start development. I'd recommend to read https://code.visualstudio.com/docs/extensions/overview manual. It is very good introduction into VS Code extensions framework.
